version: "3"
services:
  simplytranslate:
    image: quay.io/pussthecatorg/simplytranslate:latest
    container_name: simplytranslate
    ports:
      - "5000:5000" # Comment Out Once Reverse Proxy is done
    volumes:
      - "/home/simplytranslate/config.conf:/etc/simplytranslate/web.conf"
